import axios from "axios";
import { chatService } from "./chatService.js";

const OLLAMA_API_URL = process.env.OLLAMA_API_URL || "http://localhost:11434";
const MODEL_NAME = process.env.MODEL_NAME || "qwen2.5:3b";

const DEFAULT_SYSTEM_PROMPT = `
You are a concise, friendly assistant.
Answer the user's question directly using only your own knowledge—no tools, no external actions.
Keep replies short unless the user asks for detail.
`.trim();

function buildMessages(history, systemPrompt, userMessage) {
  const historyMessages = Array.isArray(history)
    ? history
        .filter((m) => m?.role && m?.content)
        .map((m) => ({
          role: m.role === "user" ? "user" : "assistant",
          content:
            typeof m.content === "string"
              ? m.content
              : JSON.stringify(m.content),
        }))
    : [];

  return [
    { role: "system", content: systemPrompt },
    ...historyMessages,
    { role: "user", content: userMessage },
  ];
}

export const basicLlamaService = {
  generateResponse: async (
    message,
    conversationHistory = [],
    systemPrompt = DEFAULT_SYSTEM_PROMPT,
    options = {},
  ) => {
    const {
      temperature = 0.4,
      maxTokens = 400,
      topP = 0.9,
      model = MODEL_NAME,
    } = options;

    try {
      if (chatService?.saveMessage) {
        await chatService.saveMessage("user", message);
      }

      const messages = buildMessages(conversationHistory, systemPrompt, message);

      const response = await axios.post(`${OLLAMA_API_URL}/api/chat`, {
        model,
        messages,
        stream: false,
        options: {
          temperature,
          num_predict: maxTokens,
          top_p: topP,
        },
      });

      const output =
        response?.data?.message?.content?.trim() ||
        "No response generated by the LLM.";

      if (chatService?.saveMessage) {
        await chatService.saveMessage("assistant", output);
      }

      return { type: "text", message: output };
    } catch (error) {
      console.error(
        "basicLlamaService error:",
        error?.response?.data || error.message,
      );
      return { type: "text", message: "Failed to generate a response." };
    }
  },
};
